# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  deploy:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
  test:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - restore_cache:
          keys:
            - bundle-install
      - checkout

      - run:
          name: install dependencies
          command: bundle install

      - save_cache:
          key: bundle-install
          paths: ~/.bundle

      # run tests!
      - run:
          name: run tests
          command: rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
